### ISSUE TITLE
Where does this.racesFS come from?

### ISSUE THREAD

**Issue by oteph** [ngxs-labs/firestore-plugin#1]
Your documentation does not explain where `this.racesFS` comes from. (Im assuming from the constructor you omitted?)

Might also be nice if you could provide a working example, in code.

**Comment by joaqcid** [comment]
hi @oteph thanks for the feedback!

i updated the readme docs, including the  `racesFS` dependency in the constructor.

regarding the example, i was thinking on writing a post with a more complete example. Once i do that i'll add it as a link in the repository.

did you find anything else not working or incomplete other than the `racesFS`?

**Comment by oteph** [comment]
One thing that i had to look up in the source was what create does, as its called set with AFS.  Also passing `merge: true` as the default forces me to extend the functionality of the class if i want the classical `set`. 
Might be better to keep the names the same as with AFS.

```typescript
public create$(id: string, value: Partial<T>) {
        return from(this.firestore.doc(`${this.path}/${id}`).set(value, { merge: true })).pipe();
    }

```

Another thing was, that for one usecase i need access to the id of the document. This gets lost as you only extract the data. Maybe add another observable that has something like {id:string, document:any} as the payload.

**Comment by joaqcid** [comment]
i see,

the idea of the FirestoreService is to provide a common and easy implementation of `angular/fire` with some basic methods.

if you need a more customised behavior, i'd suggest creating a custom service  (in fact, for my app m using  a custom service)

 great feedback! hope you like the library! are you using it already or just dabbling with it?

thanks!
