### ISSUE TITLE
Unable to resolve dependency tree

### ISSUE THREAD

**Issue by francotc** [ngxs-labs/firestore-plugin#106]
My versions:

* "@angular/core": "^18.2.12", (also issue with angular 19)
* "@angular/fire": "^18.0.1",

```
npm error Found: @angular/fire@18.0.1
npm error node_modules/@angular/fire
npm error   @angular/fire@"^18.0.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @angular/fire@">=7.0.0 <8.0.0" from @ngxs-labs/firestore-plugin@18.0.2
npm error node_modules/@ngxs-labs/firestore-plugin
```

**Comment by francotc** [comment]
I was able to fix it with overrides like this in the `package.json`, if its helpful for someone:
```
  "overrides": {
    "@ngxs-labs/firestore-plugin": {
      "@angular/fire": "$@angular/fire",
      "@ngxs/store": "$@ngxs/store",
      "firebase": ">=9.0.0"
    }
  }
```
However, it would be great if you could update the library.

**Comment by francotc** [comment]
Would be great too if you could provide the new `withNgxsFirestore` for `provideStore`

**Comment by joaqcid** [comment]
@francotc ill work on it, thanks!

**Comment by joaqcid** [comment]
@francotc try updating the `@ngxs-labs/firestore-plugin` to 18.0.3 and let me know if that works without the package.json overrides, thanks!

**Comment by joaqcid** [comment]
@francotc by the way `provideNgxsFirestore` already is provided in v18 of the `@ngxs-labs/firestore-plugin`

**Comment by francotc** [comment]
Great, thanks. It's working now
