### ISSUE TITLE
Size of bundle

### ISSUE THREAD

**Issue by call-me-adas** [ngxs-labs/firestore-plugin#19]
Hi, Is there any chance to optimize size of this package? It is actually around 800 kB

**Comment by joaqcid** [comment]
@call-me-adas hi, we'll definitely look into this, btw, where are you seeing that bundle size?
this is what i can see. [size](https://bundlephobia.com/result?p=@ngxs-labs/firestore-plugin@0.1.27)

**Comment by call-me-adas** [comment]
I am using ng 11, so when i am making my prod release i see the size after adding this lib. However i think problem is in firebase package, and it is mentioned here: https://github.com/firebase/firebase-js-sdk/issues/332
