### ISSUE TITLE
NGXS_FIRESTORE_MODULE_OPTIONS is not exported in the public-api.ts

### ISSUE THREAD

**Issue by codemile** [ngxs-labs/firestore-plugin#20]
# Summary

The NGXS_FIRESTORE_MODULE_OPTIONS injection token is not exported publicly in the library.

# Problem

You can not modify the constructor parameters of a derived class.

```
import {AngularFirestore} from '@angular/fire/firestore';
import {NGXS_FIRESTORE_MODULE_OPTIONS, NgxsFirestoreModuleOptions} from '@ngxs-labs/firestore-plugin/lib/utils';

@Injectable({providedIn: 'root'})
export class ExampleService extends NgxsFirestore<ExampleDocy> {
    public constructor(
        @Inject(AngularFirestore)  firestore: AngularFirestore,
        @Inject(Store) store: Store,
        @Optional() @Inject(NGXS_FIRESTORE_MODULE_OPTIONS) options: NgxsFirestoreModuleOptions
    ) {
        super(firestore, store, options);
    }
}
```

The above will raise the following compiler errors.

```
Error: ./src/example.service.ts
Module not found: Error: Can't resolve '@ngxs-labs/firestore-plugin/lib/utils' in '\src\example'
```

The problem is that the `@Inject(NGXS_FIRESTORE_MODULE_OPTIONS)` type is an *internal* type of the library. It's not exposed via the `public-api.ts` so that it can be imported via `@angular/fire/firestore`.

# Work Around

I can get around this issue by making the injection of the options `undefined`.

```
    public constructor(
        @Inject(AngularFirestore)  firestore: AngularFirestore,
        @Inject(Store) store: Store
    ) {
        super(firestore, store, undefined);
    }
```

I can't find any documentation what the side effects of this would be.

**Comment by joaqcid** [comment]
hi @codemile, we have an PR to improve this, using an adapter dependency to add BaseClass dependencies, 

passing `undefined` wont case any problems, that dependency is used to pass options to the service, and passing `undefined` will use default values

What is your use case to need to use the constructor? do you need to include an extra dependency?

**Comment by codemile** [comment]
@joaqcid thank for the quick response.

My service handles an action that uploads files to Firebase Storage, and I need to inject AngularFireStorage. Arguably, I could split this to a different service, but I'm trying to use a single class to handle all actions for a Firebase resource. These are just common pains you get when extending a class from a third-party. I could probably solve this in many other ways.

```
    public constructor(
        private readonly _storage: AngularFireStorage,
        @Inject(AngularFirestore)  firestore: AngularFirestore,
        @Inject(Store) store: Store
    ) {
        super(firestore, store, undefined);
    }
```

**Comment by joaqcid** [comment]
ok, makes sense, your workaround will work fine, 

i'll let you know once we improve the dependencies for the `NgxsFirestore`

**Comment by joaqcid** [comment]
@codemile fyi, the new dependency model for NgxsFirestore has been released, let me know if that works for you!

**Comment by joaqcid** [comment]
@Krismix1 glad you could make it work
