### ISSUE TITLE
Can't find how to connect to a collection with some constraints?

### ISSUE THREAD

**Issue by jgrossrieder** [ngxs-labs/firestore-plugin#23]
Hi,

Thank you for your awesome library, it renders so many things so much simpler than NGRX :)
One thing I struggle is being able to connect to a connection, with some constraints.

I've a collection of documents(named "trips"), and for each item there are some roles:

the type of my document:

```
export interface Trip {
  id: string;
  ownerUid: string;
  sharedUids: string[];
  name: string;
  startDate: Date;
}
```

And I need to get all documents, for which I'm the owner, writer or reader.

With angularfire, it would gives something like this: 
const user = firebase.auth().currentUser;
const query = db.collection("trips").where("sharedUids", "array-contains", user.uid);

How can I add this kind of where in NGXS-labs?

**Comment by joaqcid** [comment]
hi @jgrossrieder 

we're glad you are enjoying and using the library

to accomplish what you need you can setup a connection like this:

```
// Action 
export class GetTripsBySharedUser{
    type = //...
}

// state
//...
export class TripsState implements NgxsOnInit {
//...
ngxsOnInit(){
    this.ngxsFirestoreConnect.connect(GetTripsBySharedUser, {
    to: () => {
        const uid = const user = firebase.auth().currentUser.uid;
        return this.tripsFirestore.collection$(ref=> ref.where("sharedUids", "array-contains", uid)))
       }
   })
}

  @Action(StreamEmitted(GetTripsBySharedUser))
  getEmitted({ setState }: StateContext<RoutesStateModel>, { action, payload }: Emitted<GetTripsBySharedUser, Trip[]>) {
    // here payload is the result of the query
  }

}


// firestore service
export class TripsFirestore extends FirestoreService<Trip> {
  basePath = 'trips';
}

```

you can also make it more generic, including a parameter to the Action constructor `GetTripsBySharedUser` and use that to filter by sharedUids in your query

hope this helps!

**Comment by jgrossrieder** [comment]
This works, thank you very much!
