### ISSUE TITLE
Firebase V9/AngularFire V7.0.4

### ISSUE THREAD

**Issue by bkr32** [ngxs-labs/firestore-plugin#41]
After updating to Angularfire V7 / firebase V9 i receive the following error on compile

```
Error: Failed to compile entry-point @ngxs-labs/firestore-plugin (`es2015` as esm2015) due to compilation errors:
node_modules/@ngxs-labs/firestore-plugin/fesm2015/ngxs-labs-firestore-plugin.js:113:26 - error NG1010: Value at position 2 in the NgModule.imports of NgxsFirestor
eModule is not a reference
  Value could not be determined statically.

113                 imports: [CommonModule, NgxsModule.forFeature([NgxsFirestoreState]), AngularFirestoreModule]
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@ngxs-labs/firestore-plugin/fesm2015/ngxs-labs-firestore-plugin.js:113:86
    113                 imports: [CommonModule, NgxsModule.forFeature([NgxsFirestoreState]), AngularFirestoreModule]
                                                                                             ~~~~~~~~~~~~~~~~~~~~~~
    Unknown reference.


Compiling @ngxs-labs/firestore-plugin : es2015 as esm2015
C:\app\node_modules\@angular\compiler-cli\ngcc\src\execution\tasks\completion.js:57
            throw new Error(createErrorMessage(fs, task, message));
            ^

Error: Failed to compile entry-point @ngxs-labs/firestore-plugin (`es2015` as esm2015) due to compilation errors:
node_modules/@ngxs-labs/firestore-plugin/fesm2015/ngxs-labs-firestore-plugin.js:113:26 - error NG1010: Value at position 2 in the NgModule.imports of NgxsFirestor
eModule is not a reference
  Value could not be determined statically.

113                 imports: [CommonModule, NgxsModule.forFeature([NgxsFirestoreState]), AngularFirestoreModule]
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@ngxs-labs/firestore-plugin/fesm2015/ngxs-labs-firestore-plugin.js:113:86
    113                 imports: [CommonModule, NgxsModule.forFeature([NgxsFirestoreState]), AngularFirestoreModule]
                                                                                             ~~~~~~~~~~~~~~~~~~~~~~
    Unknown reference.
```

**Comment by joaqcid** [comment]
hi @bkr32 we havent yet releases a version compatible with latest `@angular/fire` and `firebase`, as soon as we release it i'll let you know.

**Comment by skotturi** [comment]
Any update on this?

**Comment by cnthiesen** [comment]
Would love an update on this as well 😄

**Comment by joaqcid** [comment]
i havent had time to get started on this yet

**Comment by skotturi** [comment]
Can we help? Is it as simple migrating the import statements over to begin? 

https://github.com/angular/angularfire/blob/master/docs/version-7-upgrade.md

**Comment by joaqcid** [comment]
hi @skotturi if you want to give it a try with a PR, would be awesome, 
ill probably be able to look at this next week

**Comment by joaqcid** [comment]
hi @bkr32 @skotturi, i've been looking into upgrading to firebase 9 and @angular/fire 7

problem is according to [this](https://github.com/angular/angularfire/blob/master/docs/version-7-upgrade.md#breaking-changes) v7 works only with Ivy so i think ill hold off with upgrading

i already have a branch withe `compat` mode working, i guess when i finally move to new version i will also include the modular version of @angular/fire

**Comment by juergenriemer** [comment]
@joaqcid any update on this? Would be great to get it working

**Comment by joaqcid** [comment]
hi @juergenriemer , 

this si the last update on this [here](https://github.com/ngxs-labs/firestore-plugin/issues/41#issuecomment-1004856374)

**Comment by leo00723** [comment]
any update on this? Is it even necessary anymore? Angularfire v7 seems to complete and keeps the stream open or am I doing something wrong?

**Comment by skotturi** [comment]
@joaqcid I tried upgrading to angular 13 from 12 today and dependencies slowly made me upgrade everything including firebase to v9 and angular/fire to v7. I couldn't get ngxs-firestore to work even after trying to manually apply the /compat path to this lib. I'm curious about what the ivy lib requirement is? If you've got a working compat version, can we start using that?

**Comment by joaqcid** [comment]
@skotturi not sure, i tried building the plugin with view engine  after the upgrade and didnt work, ill look again to this and try to establish a plan to support new firebase version

**Comment by bkr32** [comment]
@joaqcid any update on this?

**Comment by markterrill** [comment]
Hi, keen on an update because I'm caught half pregnant and trying to use the various forks with v12/13 isn't working well!

**Comment by markterrill** [comment]
Hi @joaqcid I think the drum keeps beating for us to keep marching on. I accidentally nudged the house of cards of dependencies upgrading Ionic Capacitor and that triggered everything towards Angular 12/13. It seems 12 is certainly the new baseline.
Maybe issue a release file as is at the current point and then move everything on to 12/13?

Also, may I ask a dumb question? How do you 'build/package' the repo for npm / yarn use? I can't work out how it was done previously, looking at ng-packagr and it's various issues and at a dead end. Seems folk with other forks have had similar issues.

**Comment by markterrill** [comment]
ps, if you have a branch working on 12/13 could you please push it?

**Comment by markterrill** [comment]
Hi, got it neatly all working with angular 12 and ionic 6. Key was the ``` "enableIvy": true``` in src/tsconfig.lib.prod.json and then it built beautifully.

**Comment by Krismix1** [comment]
Want to chime in as well on this issue.
We also wanted to update the libraries and got blocked due to Firebase v9 and this package not being compatible.
I have managed to make it work using @markterrill 's fork with a few changes.

> im still thinking if this is the way we want to go moving forward... any thoughts?

My opinion is that this version should be marked as a major version bump (assuming semantic versioning) and a separate branch be created for the current version in case bug/security fixes would need to be backported.

**Comment by markterrill** [comment]
Great. Do you want to submit a PR? I’m also wondering if my fork is latest, I’ll check when I get back!

**Comment by Krismix1** [comment]
Yes, I can try to do that during the weekend.

**Comment by joaqcid** [comment]
sorry for not responding these last weeks, i already have a branch working with latest angular/fire and firebase versions.

i havent published it yet since i didnt want to tie the plugin with any specific version

the alternate option to keep the plugin agnostic of firebase and angular/fire version, is to release a new package with just the NgxsFirestoreService, what do you guys think about doing this?

**Comment by markterrill** [comment]
That's fine by me, though simple is most often the easiest. I agree with @Krismix1 in that it could simply be a new major version with a clear readme header saying it's a compatibility release. If then new features are added, people *could* backport, but realistically how likely is it that they simply won't upgrade? Angular 12/13 is the new norm and you need the matching Firebase versions.

**Comment by skotturi** [comment]
I vote for v2 of this plugin to support angular 12+ and if anyone needs ng11, they can use v1.36

**Comment by blackfan23** [comment]
I agree. If you need an older version you can always use a previous release of this plugin as well, but realistically, sooner or later you upgrade your angular and want the features provided by the latest iterations of angularfire as well.

**Comment by BL-marcusrogers** [comment]
Another vote to release as v2 as long as it's clearly documented in the readme.

**Comment by joaqcid** [comment]
hi all, v1.0.0 has been released, compatible with latest firebase 9 and @angular/fire

thank you all!

**Comment by BL-marcusrogers** [comment]
Trying to upgrade to v1.0.0. When running in a CICD pipeline (full npm install) I'm getting an error when I have @ngxs/store version greater than 3.6.2. Error is:

```Error: node_modules/@ngxs-labs/firestore-plugin/lib/ngxs-firestore.module.d.ts:10:106 - error TS2339: Property 'ɵbc' does not exist on type 'typeof import("/******/node_modules/@ngxs/store/ngxs-store")'.```

**Comment by joaqcid** [comment]
@BL-marcusrogers which version of angular and @angular/fire do you have?

**Comment by BL-marcusrogers** [comment]
@joaqcid

Angular v12.1.4
@angular/fire v7.4.1
firebase v9.9.0
@ngxs/store 3.7.4.

I tried switching to:

@angular/fire v7.2.0
firebase v9.4.0
@ngxs/store 3.7.2

as I see that's what is referenced in the source code, but same result. When I initially updated all my packages it built fine on my local machine, probably because of package versions I already had installed. But doing a clean install in my CI/CD pipeline fails. I'm going to try with a fresh Angular project to see if I can re-create.

There's also a StackOverflow (https://stackoverflow.com/questions/72619037/error-ts2339-property-%c9%b5bc-does-not-exist-on-type-typeof-import) from June of people getting the same error with @ngxs/store (but not the firestore plugin). No resolution there. Thanks for taking a look.

**Comment by BL-marcusrogers** [comment]
@joaqcid ok, I've recreated this in a blank Angular project:

package.json:
```
{
  "name": "store",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.1.1",
    "@angular/common": "~12.1.1",
    "@angular/compiler": "~12.1.1",
    "@angular/core": "~12.1.1",
    "@angular/fire": "~7.2.0",
    "@angular/forms": "~12.1.1",
    "@angular/platform-browser": "~12.1.1",
    "@angular/platform-browser-dynamic": "~12.1.1",
    "@angular/router": "~12.1.1",
    "@ngxs-labs/firestore-plugin": "~1.0.0",
    "@ngxs/store": "~3.7.2",
    "firebase": "~9.4.0",
    "rxjs": "~6.6.0",
    "tslib": "~2.2.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.1.1",
    "@angular/cli": "~12.1.1",
    "@angular/compiler-cli": "~12.1.1",
    "@types/jasmine": "~3.6.0",
    "@types/node": "~12.11.1",
    "jasmine-core": "~3.8.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.5.0",
    "typescript": "~4.3.2"
  }
}
```

app.module.ts:
```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

import { NgxsModule } from '@ngxs/store';
import { NgxsFirestoreModule } from '@ngxs-labs/firestore-plugin';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    NgxsModule.forRoot(
      [
      ],
      {
        developmentMode: true,
      }
    ),
    NgxsFirestoreModule.forRoot(),
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

run `npm i` then `npm run build`

error is:
```
Error: node_modules/@ngxs-labs/firestore-plugin/lib/ngxs-firestore.module.d.ts:10:106 - error TS2339: Property 'ɵbc' does not exist on type 'typeof import("/******/store/node_modules/@ngxs/store/ngxs-store")'.

10     static ɵmod: i0.ɵɵNgModuleDeclaration<NgxsFirestoreModule, never, [typeof i1.CommonModule, typeof i2.ɵbc, typeof i3.AngularFirestoreModule], never>;
```

If you drop down to @ngxs/store version 3.6.2 (and install using `npm i --legacy-peer-deps`) the build succeeds, but of course that version is so old it has a lot of incompatibilities with Angular 12 and other packages once you start writing actual code.

Let me know if I can provide any other details.

**Comment by joaqcid** [comment]
the only difference vs the plugin repo is that angular is at 12.2.15, can you try updating to that version?

**Comment by BL-marcusrogers** [comment]
@joaqcid I updated to angular 12.2.15. Same error.

**Comment by BL-marcusrogers** [comment]
@joaqcid Here's a stackblitz - it uses Angular 14, but same error: https://angular-ivy-m1hwk9.stackblitz.io. As soon as you remove the NgxsFirestoreModule reference in the imports section of app.module.ts, the application runs.

**Comment by BL-marcusrogers** [comment]
@joaqcid Looks good with 3.7.2. It's really close with 3.7.4 and Angular 14 - I just have to make two small changes in the package once it's loaded into node_modules and everything seems to run fine. I'll stick with 3.7.2 and Angular 12 for now. Thanks!

**Comment by miguelromeroh** [comment]
I feel like this plugin cant keep up with ngxs or firebase

**Comment by joaqcid** [comment]
hi @miguelromeroh , could you elaborate what you mean?

i did a quick investigation to find if it would be possible to use new firebase 9 methods and syntax without interfering with current API, but looks like that is not possible, 

my thoughts around this are, 
- release maybe a new plugin version using firebase 9 new syntax
- split the plugin in the "connect" part (agnostic of firebase) and another package with the firestore service

would love everybody's your input on this

thanks

**Comment by BL-marcusrogers** [comment]
@joaqcid Would it be possible to split it like the AngularFire package does? have a `compat` folder that works with Firebase <= 8 while the root works with Firebase 9 (modular)? If not, a new plugin version would be fine with the same documentation stipulation as the last version bump (make it clear that if you aren't on Firebase 9 you need to use a previous version).

**Comment by fadingbeat** [comment]
Anything new going on with the plugin? NGXS store is now on version 3.7.6. 
I encountered the same error as [BL-marcusrogers](https://github.com/BL-marcusrogers), it doesn't seem right to downgrade ngxs store to 3.7.2. which might not even solve the issue.
