### ISSUE TITLE
Disconnect and Reconnect for "refresh" functionality

### ISSUE THREAD

**Issue by skotturi** [ngxs-labs/firestore-plugin#42]
I want to be able to disconnect and reconnect my current state. Right now I have 4 subcollections (so they each have an NGXSFirestore Connection). Each of these subcollections have their own State. A "parent" state then uses `combineLatest` to merge all 4 subcollection states.

To "refresh", I'm disconnecting all the 4 subcollection streams, then clearing their associated states. Then reconnecting. This is causing all sorts of missing data issues. Chrome Redux devtools shows no data being repopulated even though data is coming back into each of the 4 subcollection states.

My current guess is that the disconnect is handling async so in the following action, the disconnect is still occurring when I try to reconnect. This breaks the redux state and maybe also breaks the zone management in angular because it doesnt detect any change in the data that's coming back in through the firestore adapter (so data is coming back into the app, its just getting lost or removed immediately). 

There's a lot of code involved but here's the "refresh" action:
```
  @Action(RefreshVillage)
  refreshVillage(ctx: StateContext<VillageStateModel>, action: GetVillage) {
    console.log('[Village State] Getting village & connecting subcollections');
    const { uid } = action.payload;
    return this.store.dispatch([
      // disconnect and clear everything first
      new DisconnectStream(GetVillage),
      new DisconnectStream(FetchBulletins),
      new DisconnectStream(FetchHangouts),
      new DisconnectStream(FetchSupportRequests),
      new DisconnectStream(FetchExchanges),
      new ClearBulletins(),
      new ClearExchanges(),
      new ClearHangouts(),
      new ClearSupportRequests(),
      new ClearAllPosts(),
      // then get new stuff
      ctx.dispatch(new GetVillage({uid}))
    ]);
  }
  
    @Action(GetVillage)
  getVillage(ctx: StateContext<VillageStateModel>, action: GetVillage) {
    console.log('[Village State] Getting village & connecting subcollections');
    const { uid } = action.payload;
    return this.store.dispatch([
      new FetchBulletins({ villageUID: uid }),
      new FetchHangouts({ villageUID: uid }),
      new FetchSupportRequests({ villageUID: uid }),
      new FetchExchanges({ villageUID: uid }),
      new BuildFeed(),
      new PostFetchComplete(),
    ]);
  }
  ```
  
Is there an async await option for `DisconnectStream`? Is this to be expected? How would you go about disconnecting and reconnecting using a simpler demo (like the Races example used in the docs)

**Comment by skotturi** [comment]
Here the state says its empty but data is being pulled from it and displayed... 
<img width="1678" alt="incorrect_state" src="https://user-images.githubusercontent.com/4960284/132816413-f579279b-df9c-4b40-9d44-031f8add1129.png">

**Comment by joaqcid** [comment]
hi @skotturi, 
the `Disconnect` action closes the open stream you specify, this happens in an rxjs pipeline that's managed by the plugin, so yes, i would expect to be async.

from the code you shared my reccomendation would be to execute disconnect, clean up and refetch in sequence, 

in order to do that i would do


```

@Action(RefreshVillage)
  refreshVillage(ctx: StateContext<VillageStateModel>, action: GetVillage) {
    console.log('[Village State] Getting village & connecting subcollections');
    const { uid } = action.payload;
    return this.store.dispatch([
      new DisconnectStream(GetVillage),
      new DisconnectStream(FetchBulletins),
      new DisconnectStream(FetchHangouts),
      new DisconnectStream(FetchSupportRequests),
      new DisconnectStream(FetchExchanges)]).pipe(
concatMap(()=> this.store.dispatch([      
new ClearBulletins(),
      new ClearExchanges(),
      new ClearHangouts(),
      new ClearSupportRequests(),
      new ClearAllPosts()
])),
concatMap(()=> this.store.dispatch([      
      // then get new stuff
      ctx.dispatch(new GetVillage({uid}))
    ]);
)
  }
```

**Comment by skotturi** [comment]
Ok thanks, that makes sense and is working locally. Appreciate the support 🙏

**Comment by skotturi** [comment]
Ok thanks, that makes sense and is working locally. Appreciate the support 🙏
