### ISSUE TITLE
Error when document uses a reference

### ISSUE THREAD

**Issue by bkr32** [ngxs-labs/firestore-plugin#44]
When attempting to fetch a document which contains the type of `reference` from firestore, the following error is returned

```
ERROR TypeError: Cannot read properties of undefined (reading 'ps')

ERROR TypeError: Cannot freeze
    at Function.freeze (<anonymous>)

zone.js:1063 Unhandled Promise rejection: Cannot assign to read only property '__zone_symbol__state' of object '[object Object]' ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot assign to read only property '__zone_symbol__state' of object '[object Object]'

zone.js:1407 Uncaught TypeError: Cannot add property 0, object is not extensible

```

Edit:
a array field within the document also contained the `reference` type

**Comment by markwhitfeld** [comment]
Hi there.
You should only be adding objects to your store that are serialisable.
You would have to convert that ref into something that makes sense to put into your store.

**Comment by joaqcid** [comment]
@bkr32 are you still having problems with this?

**Comment by bkr32** [comment]
@joaqcid decided not to go with it
