### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by dj-fiorex** [ngxs-labs/firestore-plugin#61]
Hello guys, i'm starting a new angular project and i would like to try NgXs for the first time and i saw this amazing repository, in fact i work with firebase  as a backend. My only question is: is this repo dead? 
Thanks!

**Comment by joaqcid** [comment]
we are alive!

**Comment by muellerdberlin** [comment]
How about upgrading to Angular 13 and/or 14?

**Comment by joaqcid** [comment]
hi @muellerdberlin you can now use latest firebase and @angular/fire version,
