### ISSUE TITLE
Small misspelling

### ISSUE THREAD

**Issue by orbitcm-marcusrogers** [ngxs-labs/firestore-plugin#77]
The `ngxsFirectoreConnections` object should be `ngxsFirestoreConnections`.

On a side note, that connections object is useful for disconnecting only certain connections. Might be nice to have a `DisconnectByObject` helper function so you could call `DisconnectAllByObject('[Races]')` or something like that. `DisconnectAll` is too global for many use cases.

**Comment by joaqcid** [comment]
hi, i merged the typo fix, will release it soon, 

regarding disconnecting on a one by one basis, you can use `new Disconnect(Action)`  to disconnect a single action

**Comment by joaqcid** [comment]
@orbitcm-marcusrogers did that help?
