### ISSUE TITLE
Error on implementation

### ISSUE THREAD

**Issue by jonathansigg** [ngxs-labs/firestore-plugin#78]
I get an error when implementing this plugin:

```./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity i2.ɵbc to symbol

Error: node_modules/@ngxs-labs/firestore-plugin/lib/ngxs-firestore.module.d.ts:9:106 - error TS2339: Property 'ɵbc' does not exist on type 'typeof import("/Users/chsb-sigg/dev/admin-poker/node_modules/@ngxs/store/ngxs-store")'.

9     static ɵmod: i0.ɵɵNgModuleDeclaration<NgxsFirestoreModule, never, [typeof i1.CommonModule, typeof i2.ɵbc], never>;```

**Comment by joaqcid** [comment]
hi, 
what version of angular are you using?

**Comment by marcos-velasquez** [comment]
![image](https://user-images.githubusercontent.com/39884122/223002062-114ba85a-e450-427b-a865-707f390cbe47.png)
![image](https://user-images.githubusercontent.com/39884122/223002196-ca63d895-b227-4009-bda8-c549516a22b1.png)
Same thing happens to me, any suggestions?

**Comment by joaqcid** [comment]
are you trying to use it as standalone components?

**Comment by joaqcid** [comment]
if you are able to provide a stackblitz that would be great

**Comment by jonathansigg** [comment]
I tried to implement it on version 12. Because newer version wont work.
And neither with version 12...
It's really depressing.

**Comment by jonathansigg** [comment]
@joaqcid can you check this out?

**Comment by joaqcid** [comment]
Yes i will take a look and let you know, been busy these last days

**Comment by joaqcid** [comment]
@jonathansigg @marcos-velasquez downgrade `@ngxs/store` to version 3.7.3 and it will work

**Comment by jonathansigg** [comment]
@joaqcid Is there no other solution as downgrade?

**Comment by joaqcid** [comment]
@jonathansigg yes there is, im working on it for the next release, hopefully it will go out soon

**Comment by joaqcid** [comment]
hmm that's weird, i was able to make it work with angular 15 and ngxs 3.7.3 

@markwhitfeld do you know of any issue between ng >= 14 and ngxs 3.7.3?

ps, i cant give an exact date, but im trying to do it as soon as i can, i hope i can do it in the next weeek

**Comment by joaqcid** [comment]
@jonathansigg try updating to version 1.2.0, ngxs 3.7.6 should work now

**Comment by Insira** [comment]
@joaqcid I'm getting this error on angular 15.2.4  

My Dependencies list. 
> "@angular/animations": "15.2.4",
> "@angular/cdk": "15.2.4",
> "@angular/common": "15.2.4",
> "@angular/compiler": "15.2.4",
> "@angular/core": "15.2.4",
> "@angular/fire": "^7.5.0",
> "@angular/forms": "15.2.4",
> "@angular/material": "15.2.4",
> "@angular/platform-browser": "15.2.4",
> "@angular/platform-browser-dynamic": "15.2.4",
> "@angular/router": "15.2.4",
> "@ngneat/until-destroy": "^9.2.2",
> "@ngxs-labs/entity-state": "^0.1.0",
> "@ngxs-labs/firestore-plugin": "^1.2.0",
> "@ngxs/logger-plugin": "^3.8.0",
> "@ngxs/store": "^3.8.0",
> "@sentry/angular": "^7.28.1",
> "@sentry/integrations": "^7.28.1",
> "rxjs": "7.8.0",
> "tslib": "^2.3.0",
> "zone.js": "0.12.0"

      
      The error I'm getting.   
      `.src/main.ts - Error: Module build failed (from ./node_modules/.pnpm/@ngtools+webpack@15.2.4_gaeoajpm3kpeqoe6vddtc3eksq/node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity i2.ɵz to symbol`

**Comment by joaqcid** [comment]
@Insira update to version 1.2.2, should work fine

**Comment by Insira** [comment]
@joaqcid updating to 1.2.2 worked. Thanks!

**Comment by jonathansigg** [comment]
@joaqcid Whats the stand here now? any news?

**Comment by joaqcid** [comment]
@jonathansigg what's the issue you are having now?

**Comment by jonathansigg** [comment]
@joaqcid I need this plugin run on Angular 14.0.0 and @ngxs/store 3.7.4

**Comment by joaqcid** [comment]
@jonathansigg have you updated to latest `@ngxs-labs/firestore-plugin` what version are you on?
