### ISSUE TITLE
Doc: How to run queries

### ISSUE THREAD

**Issue by verygreenboi** [ngxs-labs/firestore-plugin#8]
Thanks for this library. I was wondering how I can listen to a specific document rather than a collection?

**Comment by joaqcid** [comment]
hi @verygreenboi just updated docs with an example to query a specific doc

you need to setup the connection like this

```
this.ngxsFirestoreConnect.connect(RacesActions.Get, {
      to: (action) => this.racesFS.doc$(action.payload)
 });
```
and dispatch the action 
```
this.store.dispatch(new RacesActions.Get(id));
```
