### ISSUE TITLE
Firebase update version

### ISSUE THREAD

**Issue by SanchoPanzaaa** [ngxs-labs/firestore-plugin#83]
Hi there, I really like the repository, but as I'm using the latest angular and though I need latest firebase app and I would really appreciate update to the version firebase 10, otherwise unexpected outcomes happens.

Is it comming any time soon ? 

Need some help ? 

Feel free to write me, 

thank you
Richard

**Comment by joaqcid** [comment]
hi @SanchoPanzaaa do you get an error when using firebase 10?

**Comment by JGSolutions** [comment]
Actually angularfire released version 16. When performing a npm install i get dependancy errors

Could not resolve dependency:
npm ERR! peer @angular/fire@">=7.0.0 <8.0.0" from @ngxs-labs/firestore-plugin@1.2.8

**Comment by JGSolutions** [comment]
Any progress on this?

**Comment by JGSolutions** [comment]
Unfortunately we will be removing this plugin from our project. Very difficult for us to upgrade to ang v17 as this plugin is causing dependancy issues.

**Comment by joaqcid** [comment]
@JGSolutions ill be working in the next two weeks to make it compatible with latest version of angular 17, would be able to tell me what errors you get when upgrading? are you just upgrading angular 17 or angular/fire too?

**Comment by JGSolutions** [comment]
Yes we updated to angV17 back in Oct. Also updated to the latest ang/fire v17 which then this plugin caused dependency issues.

Just create a ang17 project with latest angular/fire and which you will reprroduce the issue

**Comment by joaqcid** [comment]
hi @JGSolutions 

i created a project with the following deps and it works for me, can you send me the lib versions you are using when it doesnt work?

`@angular/*: "17"`
`@ngxs/store: "3.8.2"`
`"@ngxs-labs/firestore-plugin": "^1.2.8"`
`"@angular/fire": "^17.0.0"`
`firebase": "^10.7.1`

**Comment by joaqcid** [comment]
ah ok, but if you want to use firebase, you need to have that library...

**Comment by JGSolutions** [comment]
ahh ok i see. Wouldn't your plugin install the firebase sdk?

**Comment by joaqcid** [comment]
no, you need to install those yourself, along with the plugin you need to install `firebase` and `@angular/fire`
