### ISSUE TITLE
How to get IDs of documents in a collection?

### ISSUE THREAD

**Issue by letXeqX** [ngxs-labs/firestore-plugin#9]
Hi, I've used Firestore a lot (but not recently) and am very interested in your library.

When I retrieve a collection with `colection$()` or `collectionOnce$()` it works great except that the payload doesn't include the IDs of the collection's documents.

This means that I can't update or delete these documents, because these methods require an ID.

Am I missing something? Or, is perhaps this functionality still to come?

I'm hoping to use your library for at least 3 projects of mine, by the way. Great work!

**Comment by joaqcid** [comment]
hi @letXeqX 

right now that option is not available in the library, but i'll add it to my to-do list, or you can contribute with PR if you want ;)

in the meantime, you can use a different service or `AngularFirestore` and use that observable to implement returning the `id`

```
this.ngxsFirestoreConnect.connect(Action, {
  to: () => // use angular firestore with a query that returns the id here
})
```

**Comment by letXeqX** [comment]
Thanks a lot - I'll try that out soon!

**Comment by joaqcid** [comment]
hi @letXeqX checkout the new `idField` feature released to accomplish this

**Comment by joaqcid** [comment]
@letXeqX https://github.com/ngxs-labs/firestore-plugin#ngxsfirestore-options
